# Generated by Django 4.2.3 on 2023-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailwindCssGameApp', '0002_useractualized_alter_game_name_delete_usergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
